import { FormEvent, useRef, useState } from 'react';
import {
  classifyTemplateManagementError,
  createWorkflowTemplate,
  fetchWorkflowTemplate,
  updateWorkflowTemplate,
} from '../api/workflowTemplates';
import { useI18n } from '../hooks/useI18n';
import { QualityLevelValue, SubstrateValue } from '../types/checklist';
import { SurfaceTypeValue } from '../types/surface';
import {
  WorkflowTemplateRead,
  WorkflowTemplateUpdatePayload,
} from '../types/workflowTemplate';
import { localizeApiError } from '../utils/apiErrors';

/**
 * Stage 13F.4 — metadata form for workflow templates (create / edit /
 * duplicate). Steps are NOT edited here (Stage 13F.5):
 * - create sends no steps (an empty template is valid; the detail explains
 *   that steps are configured separately);
 * - duplicate copies the source steps verbatim, in order (price item,
 *   required/optional, note, wait) -- repeated PriceItems stay repeated;
 * - edit PATCHes only changed metadata fields.
 * The template code is always generated by the server.
 */

export type TemplateFormMode = 'create' | 'edit' | 'duplicate';

interface WorkflowTemplateFormProps {
  mode: TemplateFormMode;
  /** Template being edited, or the duplicate source. */
  source?: WorkflowTemplateRead;
  /** Localized display name of `source` (for placeholders / copy name). */
  sourceName?: string;
  onSaved: (template: WorkflowTemplateRead) => void;
  onCancel: () => void;
}

const SURFACES: SurfaceTypeValue[] = ['WALL', 'CEILING', 'FLOOR', 'OTHER'];
const SUBSTRATES: SubstrateValue[] = [
  'CONCRETE', 'GYPSUM_PLASTER', 'CEMENT_LIME_PLASTER', 'GYPSUM_BOARD', 'PAINTED', 'OTHER',
];
const QUALITY: QualityLevelValue[] = ['S1', 'S2', 'S3', 'S4', 'Q1', 'Q2', 'Q3', 'Q4'];

function sameSet<T>(a: T[], b: T[]): boolean {
  return a.length === b.length && a.every((value) => b.includes(value));
}

export function WorkflowTemplateForm({ mode, source, sourceName, onSaved, onCancel }: WorkflowTemplateFormProps) {
  const { t } = useI18n();
  const isEdit = mode === 'edit' && !!source;
  const builtinName = isEdit && !!source?.name_key; // a built-in may fall back to its localized name
  const [name, setName] = useState(
    mode === 'duplicate' ? `${sourceName ?? ''} — ${t.processes.copy_suffix}` : (source?.display_name ?? ''),
  );
  const [description, setDescription] = useState(mode === 'create' ? '' : (source?.description ?? ''));
  const [surfaces, setSurfaces] = useState<SurfaceTypeValue[]>(source?.applies_to_surface_types ?? []);
  const [substrates, setSubstrates] = useState<SubstrateValue[]>(source?.applies_to_substrates ?? []);
  const [quality, setQuality] = useState<QualityLevelValue[]>(source?.applies_to_quality ?? []);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<{ text: string; detail: string | null } | null>(null);
  const inFlight = useRef(false);

  const archivedSteps = mode === 'duplicate'
    ? (source?.steps ?? []).filter((s) => !s.price_item || s.price_item.is_archived).length
    : 0;

  const toggle = <T,>(list: T[], value: T, set: (next: T[]) => void) =>
    set(list.includes(value) ? list.filter((v) => v !== value) : [...list, value]);

  const surfaceLabel: Record<SurfaceTypeValue, string> = {
    WALL: t.surfaces.wall, CEILING: t.surfaces.ceiling, FLOOR: t.surfaces.floor, OTHER: t.surfaces.other,
  };
  const substrateLabel = (value: SubstrateValue): string => {
    const key = `substrate_${value.toLowerCase()}` as keyof typeof t.inspections;
    return String(t.inspections[key] ?? value);
  };

  const errorFor = (err: unknown) => {
    const kind = classifyTemplateManagementError(err);
    const text = {
      network: t.processes.error_network,
      stale_steps: t.processes.error_save,
      price_item_not_found: t.processes.error_save,
      not_found: t.processes.error_not_found,
      name_required: t.processes.error_name_required,
      quality_scale: t.processes.error_quality_scale,
      archived_item: t.processes.error_archived_item,
      validation: t.processes.error_save,
      other: t.processes.error_save,
    }[kind];
    const raw = localizeApiError(err, t);
    return { text, detail: kind === 'validation' || kind === 'other' ? raw : null };
  };

  const buildPatch = (): WorkflowTemplateUpdatePayload => {
    if (!source) return {};
    const patch: WorkflowTemplateUpdatePayload = {};
    const trimmed = name.trim();
    if (trimmed !== (source.display_name ?? '')) patch.display_name = trimmed || null;
    const desc = description.trim();
    if (desc !== (source.description ?? '').trim()) patch.description = desc || null;
    if (!sameSet(surfaces, source.applies_to_surface_types)) patch.applies_to_surface_types = surfaces;
    if (!sameSet(substrates, source.applies_to_substrates)) patch.applies_to_substrates = substrates;
    if (!sameSet(quality, source.applies_to_quality)) patch.applies_to_quality = quality;
    return patch;
  };

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (inFlight.current) return;
    const trimmed = name.trim();
    if (!trimmed && !builtinName) {
      setError({ text: t.processes.error_name_required, detail: null });
      return;
    }
    if (archivedSteps > 0) return; // explained below; the server would reject it anyway
    inFlight.current = true;
    setSaving(true);
    setError(null);
    try {
      let saved: WorkflowTemplateRead;
      if (isEdit && source) {
        const patch = buildPatch();
        saved = Object.keys(patch).length > 0 ? await updateWorkflowTemplate(source.id, patch) : source;
      } else {
        saved = await createWorkflowTemplate({
          display_name: trimmed,
          description: description.trim() || null,
          applies_to_surface_types: surfaces,
          applies_to_substrates: substrates,
          applies_to_quality: quality,
          steps: mode === 'duplicate'
            ? (source?.steps ?? []).map((s) => ({
                price_item_id: s.price_item_id,
                is_optional: s.is_optional,
                note: s.note, // stored text, verbatim (never the localized rendering)
                wait_after_hours: s.wait_after_hours,
              }))
            : [],
        });
      }
      // Canonical server state, not optimistic local state.
      onSaved(await fetchWorkflowTemplate(saved.id));
    } catch (err) {
      setError(errorFor(err));
    } finally {
      inFlight.current = false;
      setSaving(false);
    }
  };

  const chip = (active: boolean) =>
    `min-h-11 px-3 text-sm font-semibold rounded-xl transition ${
      active ? 'bg-blue-600 text-white shadow-sm' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
    }`;

  const title = mode === 'create' ? t.processes.create_title
    : mode === 'duplicate' ? t.processes.duplicate_title : t.processes.edit_title;

  return (
    <form aria-label={`process-form-${mode}`} onSubmit={submit} className="space-y-4" noValidate>
      <h3 className="text-base font-bold text-slate-900 break-words">{title}</h3>
      {mode === 'duplicate' && (
        <p className="rounded-xl bg-blue-50 text-blue-900 p-3 text-xs break-words">
          {t.processes.duplicate_info.replace('{count}', String(source?.steps.length ?? 0))}
        </p>
      )}
      {mode === 'create' && (
        <p className="rounded-xl bg-blue-50 text-blue-900 p-3 text-xs break-words">{t.processes.create_info}</p>
      )}

      <label className="block space-y-1">
        <span className="block text-sm font-medium text-slate-700">
          {t.processes.field_name}
          {!builtinName && ' *'}
        </span>
        <input
          aria-label="process-field-name"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder={builtinName ? sourceName : undefined}
          maxLength={255}
          className="w-full min-h-11 px-3 rounded-xl border border-slate-300 text-sm"
        />
        {builtinName && <span className="block text-xs text-slate-500 break-words">{t.processes.name_builtin_hint}</span>}
      </label>

      <label className="block space-y-1">
        <span className="block text-sm font-medium text-slate-700">{t.processes.field_description}</span>
        <textarea
          aria-label="process-field-description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          maxLength={4000}
          rows={4}
          className="w-full px-3 py-2 rounded-xl border border-slate-300 text-sm"
        />
        {isEdit && source?.description_key && (
          <span className="block text-xs text-slate-500 break-words">{t.processes.description_builtin_hint}</span>
        )}
      </label>

      <fieldset className="space-y-1">
        <legend className="text-sm font-medium text-slate-700">{t.processes.surfaces_label}</legend>
        <div className="flex flex-wrap gap-2">
          {SURFACES.map((value) => (
            <button key={value} type="button" aria-pressed={surfaces.includes(value)}
              aria-label={`process-field-surface-${value}`} className={chip(surfaces.includes(value))}
              onClick={() => toggle(surfaces, value, setSurfaces)}>
              {surfaceLabel[value]}
            </button>
          ))}
        </div>
      </fieldset>

      <fieldset className="space-y-1">
        <legend className="text-sm font-medium text-slate-700">{t.processes.substrates_label}</legend>
        <div className="flex flex-wrap gap-2">
          {SUBSTRATES.map((value) => (
            <button key={value} type="button" aria-pressed={substrates.includes(value)}
              aria-label={`process-field-substrate-${value}`} className={chip(substrates.includes(value))}
              onClick={() => toggle(substrates, value, setSubstrates)}>
              {substrateLabel(value)}
            </button>
          ))}
        </div>
      </fieldset>

      <fieldset className="space-y-1">
        <legend className="text-sm font-medium text-slate-700">{t.processes.quality_label}</legend>
        <div className="flex flex-wrap gap-2">
          {QUALITY.map((value) => (
            <button key={value} type="button" aria-pressed={quality.includes(value)}
              aria-label={`process-field-quality-${value}`} className={chip(quality.includes(value))}
              onClick={() => toggle(quality, value, setQuality)}>
              {value}
            </button>
          ))}
        </div>
        <span className="block text-xs text-slate-500 break-words">{t.processes.filters_hint}</span>
      </fieldset>

      {archivedSteps > 0 && (
        <p role="alert" className="text-sm text-red-600 break-words">
          {t.processes.duplicate_archived_block.replace('{count}', String(archivedSteps))}
        </p>
      )}
      {error && (
        <div role="alert" aria-label="process-form-error" className="space-y-1">
          <p className="text-sm font-semibold text-red-600 break-words">{error.text}</p>
          {error.detail && error.detail !== error.text && (
            <p className="text-xs text-red-600 break-words">{error.detail}</p>
          )}
        </div>
      )}

      <div className="grid grid-cols-2 gap-2">
        <button type="button" onClick={onCancel} disabled={saving}
          className="w-full min-h-11 px-3 rounded-xl border border-slate-300 bg-white text-sm font-semibold text-slate-700 disabled:opacity-60">
          {t.common.cancel}
        </button>
        <button type="submit" aria-label="process-form-submit" disabled={saving || archivedSteps > 0}
          className="w-full min-h-11 px-3 rounded-xl bg-blue-600 text-white text-sm font-semibold disabled:opacity-60">
          {saving ? t.common.saving : mode === 'create' ? t.processes.create_submit
            : mode === 'duplicate' ? t.processes.duplicate_submit : t.common.save}
        </button>
      </div>
    </form>
  );
}
